library:
  source-dirs: src
tests:
  AdventOfCode2019-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2019
copyright: 2019 Sergey Petrov
maintainer: example@example.com
dependencies:
- containers
- hspec
- base >= 4.7 && < 5
name: AdventOfCode2019
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Sergey Petrov
github: SergeyAPetrov/AdventOfCode2019
license: MIT
executables:
  AdventOfCode2019-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2019
description: Please see the README on GitHub at <https://github.com/SergeyAPetrov/AdventOfCode2019#readme>
